--- 
abstract: Manage and minify .css and .js assets in a Catalyst application
author: 
  - Robert Krimen <rkrimen@cpan.org>
build_requires: 
  Catalyst::Test: 0
  Directory::Scratch: 0
  FindBin: 0
  HTML::Declare: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Assets
no_index: 
  directory: 
    - inc
    - t
requires: 
  CSS::Minifier: 0
  Catalyst: 0
  Class::Accessor::Fast: 0
  File::Assets: 0.050
  JavaScript::Minifier: 0
version: 0.030
