---
name: Catalyst-Plugin-Assets
version: 0.011
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: Manage and minify .css and .js assets in a Catalyst application
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CSS::Minifier: 0
  Catalyst: 0
  Class::Accessor::Fast: 0
  File::Assets: 0
  JavaScript::Minifier: 0
build_requires:
  Catalyst::Test: 0
  Directory::Scratch: 0
  FindBin: 0
  Test::More: 0
provides:
  Catalyst::Plugin::Assets:
    file: lib/Catalyst/Plugin/Assets.pm
    version: 0.011
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
